[book]
authors = ["LinuxBoot authors"]
language = "en"
multilingual = false
src = "src"
title = "LinuxBoot"

[output.html]
cname = "book.linuxboot.org"
git-repository-url = "https://github.com/linuxboot/book"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
