[book]
authors = ["LinuxBoot authors"]
src = "src"
title = "LinuxBoot"

[output.html]
cname = "book.linuxboot.org"
git-repository-url = "https://github.com/linuxboot/book"
additional-css = [
    "theme/css/language-picker.css",
]
additional-js = [
    "mermaid.min.js",
    "mermaid-init.js",
    "theme/js/language-picker.js",
]

[build]
extra-watch-dirs = ["po"]

[output.linkcheck]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.gettext]
after = ["links"]
